### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by nick-json** [toowake/nexus#9]
Let's dockerize this application, so one doesn't have to manually install every npm package listed in package.json.

Website:
https://docker.com/

Tutorial:
https://youtu.be/gAkwW2tuIqE?si=FaCUqje5p8SqsHPq

**Comment by semi-constructor** [comment]
Hello Nick,
after reviewing your issue, we have decided to not directly add the docker setup since for beginners it will be to hard to understand. We have added the Docker files into the README.md if anyone is interested.

Best regards,
cptcr | Head Management
